---
default_language_version:
  python: /home/runner/work/suzieq/suzieq/.venv/bin/python

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending


  - repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        exclude: >
          (?x)^(
              suzieq/db/.*|
              suzieq/gui/.*|
              suzieq/restServer/.*|
              tests/.*
          )$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
